apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: hacbs-demo-test-app-zjiy
    appstudio.openshift.io/component: test-component-qpzf
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: test-component-qpzf
  namespace: hacbs-e2e-iogp
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_psturc-org_devfile-sample-hello-world
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/psturc-org/devfile-sample-hello-world
